name: disruptum
favicon: null
layout_spectrum: 0.19769184524193406
typography_spectrum: 0.2534159682691097
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9052545211743563
  lightness: 0.5995484788436443
  saturation: 0.10560909868218005
  rhythmicContrast: 0.24256662325933576
purpose: []
